auto: true
server: true
permalink: none
baseurl: ""
exclude:
- .gitignore
- README.md

prose:
  rooturl: "_posts/articles"
  metadata:
    _posts/articles: |
      title: Your Post Title
      abstract: Short summary of your article.
      published: false
      comments: true
      author_twitter: sebdeckers
      author: Sebastiaan Deckers
      layout: article
      categories:
      - articles